//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "favorite")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub f_id: i64,
    pub name: String,
    pub path: String,
    pub created_at: String,
    pub latest_row_at: String,
    pub enabled: bool,
    pub scan_deleted_videos: bool,
    pub include_keywords: Option<String>,
    pub exclude_keywords: Option<String>,
    pub min_duration_seconds: Option<i32>,
    pub max_duration_seconds: Option<i32>,
    pub min_page_duration_seconds: Option<i32>,
    pub max_page_duration_seconds: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
