//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod collection;
pub mod config_item;
pub mod favorite;
pub mod page;
pub mod submission;
pub mod task_queue;
pub mod video;
pub mod video_source;
pub mod watch_later;
